
;this file for FamiTone2 library generated by FamiStudio
FT_DPCM_PTR=$c000
	.export _akj_music_data
_akj_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $70 ;instrument 00 (Instrument 5)
	.word @env1, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Stutter)
	.word @env2, @env0, @env0
	.byte $00

@samples:
@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c7,$06,$c6,$03,$c5,$02,$c4,$03,$c3,$06,$c2,$03,$c1,$00,$0c
@env2:
	.byte $cf,$ce,$cb,$c3,$c0,$00,$04

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $f9,$f9,$cb
@ref1:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref2:
	.byte $80,$22,$f9,$a3,$22,$f9,$a3
@ref3:
	.byte $24,$f9,$a3,$24,$f9,$a3
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref4:
	.byte $82,$4e,$a5,$52,$a5,$4e,$91,$4e,$91,$52,$a5,$4e,$a5,$52,$a5,$4e,$91,$4e,$91,$52,$a5
@ref5:
	.byte $52,$a5,$54,$a5,$52,$91,$52,$91,$54,$a5,$52,$a5,$54,$a5,$52,$91,$52,$91,$54,$a5
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref6:
	.byte $f9,$f9,$cb
@ref7:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref8:
	.byte $f9,$f9,$cb
@ref9:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch4loop

@song1ch0:
	.byte $fb, $01
@song1ch0loop:
@ref10:
	.byte $80,$10,$cd,$14,$f9,$f1,$00
@ref11:
	.byte $10,$cd,$14,$f9,$f1,$00
	.byte $ff,$06
	.word @ref11
@ref12:
	.byte $1a,$cb,$16,$cd,$10,$cf,$0c,$a5,$10,$a5
@ref13:
	.byte $1e,$f9,$a5,$24,$f9,$a1
@ref14:
	.byte $22,$f9,$f9,$c9
	.byte $ff,$06
	.word @ref13
@ref15:
	.byte $2c,$f9,$f9,$c9
	.byte $ff,$06
	.word @ref11
	.byte $ff,$06
	.word @ref11
	.byte $ff,$06
	.word @ref11
	.byte $ff,$0a
	.word @ref12
	.byte $ff,$06
	.word @ref13
@ref16:
	.byte $22,$f9,$f9,$c9
	.byte $ff,$06
	.word @ref13
@ref17:
	.byte $2c,$f9,$f9,$c9
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref18:
	.byte $f9,$f9,$cb
@ref19:
	.byte $f9,$f9,$cb
@ref20:
	.byte $f9,$f9,$cb
@ref21:
	.byte $f9,$f9,$cb
@ref22:
	.byte $f9,$f9,$cb
@ref23:
	.byte $f9,$f9,$cb
@ref24:
	.byte $f9,$f9,$cb
@ref25:
	.byte $f9,$f9,$cb
@ref26:
	.byte $f9,$f9,$cb
@ref27:
	.byte $f9,$f9,$cb
@ref28:
	.byte $f9,$f9,$cb
@ref29:
	.byte $f9,$f9,$cb
@ref30:
	.byte $f9,$f9,$cb
@ref31:
	.byte $f9,$f9,$cb
@ref32:
	.byte $f9,$f9,$cb
@ref33:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref34:
	.byte $f9,$f9,$cb
@ref35:
	.byte $f9,$f9,$cb
@ref36:
	.byte $f9,$f9,$cb
@ref37:
	.byte $f9,$f9,$cb
@ref38:
	.byte $f9,$f9,$cb
@ref39:
	.byte $f9,$f9,$cb
@ref40:
	.byte $f9,$f9,$cb
@ref41:
	.byte $f9,$f9,$cb
@ref42:
	.byte $f9,$f9,$cb
@ref43:
	.byte $f9,$f9,$cb
@ref44:
	.byte $f9,$f9,$cb
@ref45:
	.byte $f9,$f9,$cb
@ref46:
	.byte $f9,$f9,$cb
@ref47:
	.byte $f9,$f9,$cb
@ref48:
	.byte $f9,$f9,$cb
@ref49:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref50:
	.byte $f9,$f9,$cb
@ref51:
	.byte $f9,$f9,$cb
@ref52:
	.byte $f9,$f9,$cb
@ref53:
	.byte $f9,$f9,$cb
@ref54:
	.byte $f9,$f9,$cb
@ref55:
	.byte $f9,$f9,$cb
@ref56:
	.byte $f9,$f9,$cb
@ref57:
	.byte $f9,$f9,$cb
@ref58:
	.byte $f9,$f9,$cb
@ref59:
	.byte $f9,$f9,$cb
@ref60:
	.byte $f9,$f9,$cb
@ref61:
	.byte $f9,$f9,$cb
@ref62:
	.byte $f9,$f9,$cb
@ref63:
	.byte $f9,$f9,$cb
@ref64:
	.byte $f9,$f9,$cb
@ref65:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref66:
	.byte $f9,$f9,$cb
@ref67:
	.byte $f9,$f9,$cb
@ref68:
	.byte $f9,$f9,$cb
@ref69:
	.byte $f9,$f9,$cb
@ref70:
	.byte $f9,$f9,$cb
@ref71:
	.byte $f9,$f9,$cb
@ref72:
	.byte $f9,$f9,$cb
@ref73:
	.byte $f9,$f9,$cb
@ref74:
	.byte $f9,$f9,$cb
@ref75:
	.byte $f9,$f9,$cb
@ref76:
	.byte $f9,$f9,$cb
@ref77:
	.byte $f9,$f9,$cb
@ref78:
	.byte $f9,$f9,$cb
@ref79:
	.byte $f9,$f9,$cb
@ref80:
	.byte $f9,$f9,$cb
@ref81:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song1ch4loop
